### ISSUE TITLE
api/v1/log does not have a default/stable content type

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/rekor#923] opened 2022-07-13 19:28 UTC
**Description**

`curl https://rekor.sigstore.dev/api/v1/log` repeatedly, and you'll either get back YAML or JSON:

```
$ curl https://rekor.sigstore.dev/api/v1/log
inactiveShards: null
rootHash: 647aaf8a826bff4420401e5466ba1dc66ddfe7beb1c56bdd19ba92ac49560628
signedTreeHead: |
  Rekor
  2937324
  ZHqvioJr/0QgQB5UZrodxm3f576xxWvdGbqSrElWBig=
  Timestamp: 1657740407163830517

  — rekor.sigstore.dev wNI9ajBEAiBBY+zWnkQ9MR/FQh2uuALH2OupiPVENnGFOT+1vNrM9gIgTvTaFnFIhbukmxwYySj20dCKsbVA65mwzUxsNMv79h4=
treeID: "3904496407287907110"
treeSize: 2937324

$ curl https://rekor.sigstore.dev/api/v1/log
{"inactiveShards":null,"rootHash":"647aaf8a826bff4420401e5466ba1dc66ddfe7beb1c56bdd19ba92ac49560628","signedTreeHead":"Rekor\n2937324\nZHqvioJr/0QgQB5UZrodxm3f576xxWvdGbqSrElWBig=\nTimestamp: 1657740408261198082\n\n— rekor.sigstore.dev wNI9ajBFAiBI4saGe0RrgEyueiZ/x0CdZ7okx39nWDPFZA9L0pyWKAIhAMYbvf8SuN3ngMF9HkFwEBBWRwel7oCWApgifNR+lC+m\n","treeID":"3904496407287907110","treeSize":2937324}
```

We should pick a default, I'd recommend JSON.

**Version**

Prod

**Comment by bobcallaway** [comment] 2022-07-18 12:18
duplicate of #593

**Closed as completed by bobcallaway** 2022-07-18 12:18 UTC
Labels: bug
